// Code generated by "stringer -type Status -trimprefix Status"; DO NOT EDIT.

package supervisor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusIdle-0]
	_ = x[StatusInitializing-1]
	_ = x[StatusRunning-2]
	_ = x[StatusStopped-3]
	_ = x[StatusError-4]
	_ = x[StatusPanic-5]
}

const _Status_name = "IdleInitializingRunningStoppedErrorPanic"

var _Status_index = [...]uint8{0, 4, 16, 23, 30, 35, 40}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
