// Code generated by "stringer -type Status -trimprefix Status"; DO NOT EDIT.

package supervisor

import "strconv"

const _Status_name = "IdleInitializingRunningTransientErrorStoppedErrorPanic"

var _Status_index = [...]uint8{0, 4, 16, 23, 37, 44, 49, 54}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
